//! The superbackup IPC wire contract.
//!
//! This module is the specification. A client in any language that can open a
//! named pipe (Windows) or a unix socket, write a line of JSON and read a line
//! of JSON can drive the daemon completely, using nothing but this file.
//!
//! # Framing
//!
//! Newline-delimited JSON. One JSON object per line, UTF-8, terminated by a
//! single `\n`. No length prefix, no envelope framing, no binary. `\r\n` is
//! tolerated on input. This costs a little parsing speed and buys a protocol
//! that can be exercised from a terminal, logged verbatim, and diffed in a bug
//! report — which for an IPC surface that humans and agents both drive is the
//! better trade.
//!
//! Lines longer than [`Limits::max_line_bytes`](super::Limits::max_line_bytes)
//! are refused; see [Denial of service](#denial-of-service).
//!
//! # Conversation
//!
//! ```text
//! server → {"type":"hello","protocol":1,"min_protocol":1,"version":"0.1.0", ...}
//! client → {"type":"request","id":1,"protocol":1,"body":{"cmd":"status"}}
//! server → {"type":"ok","id":1,"body":{"reply":"status","snapshot":{...}}}
//! client → {"type":"request","id":2,"protocol":1,"body":{"cmd":"subscribe","topics":["progress"]}}
//! server → {"type":"ok","id":2,"body":{"reply":"subscribed","subscription":2,"topics":["progress"]}}
//! server → {"type":"stream","id":2,"body":{"kind":"progress", ...}}
//! server → {"type":"stream","id":2,"body":{"kind":"progress", ...}}
//! client → {"type":"cancel","id":2}
//! server → {"type":"end","id":2}
//! ```
//!
//! The server sends [`ServerFrame::Hello`] unprompted, immediately on accept,
//! before the client says anything. That makes version negotiation a property
//! of the connection rather than of the first request: a client that cannot
//! speak the daemon's protocol learns so before it has sent a passphrase or a
//! destructive command.
//!
//! Every request carries a client-chosen `id`. Responses, stream items and the
//! terminating `end` all echo it. Ids are scoped to one connection and only
//! need to be unique among that connection's *outstanding* requests; reusing
//! an id whose response has already arrived is legal, and monotonic counting
//! is the obvious implementation. Requests may be pipelined and the daemon may
//! answer them out of order, which is precisely why the id exists.
//!
//! # Requests
//!
//! [`Request`] is internally tagged: `{"cmd":"job.run","job":"docs","dry_run":false}`.
//! The command name and its parameters live in one flat object, so a request
//! can be typed by hand. Command names are dotted (`job.run`, `vault.unlock`)
//! purely to group the surface for humans and for shell completion; the
//! dispatcher treats the whole string as one opaque key.
//!
//! # Responses
//!
//! Exactly one of:
//!
//! * `{"type":"ok","id":N,"body":{"reply":"<tag>", ...}}` — a typed
//!   [`Reply`]. The `reply` tag tells the caller which payload shape follows,
//!   and [`CommandSpec::reply`](super::CommandSpec::reply) says in advance
//!   which tag a given command produces.
//! * `{"type":"error","id":N,"body":{"code":"locked","message":"...","hint":"..."}}`
//!   — an [`ErrorPayload`]. `code` is a [`crate::error::ErrorCode`], a closed
//!   set that a caller can exhaustively branch on. `message` and `hint` are
//!   for humans and are not stable.
//!
//! A caller must never parse `message`. That is what `code` is for.
//!
//! # Discovery
//!
//! `{"cmd":"schema"}` returns [`Schema`]: every command, its
//! parameters, their types, one-line descriptions, and behavioural flags. It
//! is generated by the same macro invocation that generates [`Request`], the
//! [`Handler`] trait and the dispatcher, so it cannot describe a command that
//! does not exist or omit one that does.
//!
//! # Secrets
//!
//! Two rules, both load-bearing.
//!
//! **Secrets go in, never out.** There is deliberately no `GetSecret`. The
//! daemon can be asked to *store* a secret ([`Request::VaultSetSecret`]) and
//! to *use* one, but there is no request that returns plaintext credential
//! material, and none will be added. The consequences are worth stating
//! plainly:
//!
//! * A GUI cannot show the user their own S3 secret key. That is intentional.
//!   Reading it back is not a feature the user needs and it is the single
//!   most valuable thing an attacker who reaches the socket could ask for.
//! * Anything that needs a secret — kopia, a git transport, an S3 request —
//!   is invoked *by the daemon*, which passes the secret through the child
//!   process environment or stdin. The secret never crosses the IPC boundary
//!   in that direction.
//! * The vault file itself is sealed and is the supported way to move secrets
//!   between machines. Exporting is an explicit, passphrase-gated file
//!   operation, not an IPC call.
//!
//! **Secrets that come in are typed as secrets.** Passphrases and keys are
//! [`SecretString`], which deserialises straight into [`crate::secret::Secret`]
//! (zeroed on drop, redacting `Debug`) rather than into a `String` that could
//! be logged, cloned into a trace span, or included in a panic message. See
//! [`SecretString`] for the residue that this does *not* eliminate.
//!
//! # Redaction
//!
//! Every outbound frame passes through [`ServerFrame::sanitise`], which runs
//! [`crate::redact::scrub`] over every field that can carry third-party text:
//! error messages and details, event messages, current paths, kopia and git
//! transport output. This is the last line of defence; the first is that
//! secrets live in [`crate::secret::Secret`] and are handed to child processes
//! out of band.
//!
//! # Denial of service
//!
//! The daemon may run as a system service. A local socket is a privilege
//! boundary, and the peer is not assumed to be friendly:
//!
//! * a line over the cap is not buffered and not truncated — the connection is
//!   closed, because a peer that sends one is broken or hostile;
//! * requests are rate limited per connection;
//! * concurrent connections are capped;
//! * a slow subscriber is disconnected from the event firehose by dropping the
//!   oldest items and telling it how many it missed, never by buffering
//!   without bound and never by blocking the engine.
//!
//! The published values are in [`Schema::limits`](super::Schema::limits) so a
//! well-behaved client can stay inside them rather than discovering them by
//! being hung up on.

use crate::error::{Error, ErrorCode, Result};
use crate::model::{
    BandwidthSettings, Destination, EncryptionSettings, Job, SecretRef, Settings, StorageProvider,
};
use crate::state::{Event, Health, JobRun, Progress, RunStatus, StatusSnapshot};
use chrono::{DateTime, Utc};
use serde::de::{self, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::path::PathBuf;
use uuid::Uuid;

use super::schema::{CommandSpec, LimitsSpec, ParamSpec, ReplySpec, Schema, TopicSpec};
use super::{Limits, MIN_PROTOCOL_VERSION, PROTOCOL_VERSION};

// ===========================================================================
// Identifiers and context
// ===========================================================================

/// Correlates a response, and every item of a stream, with the request that
/// caused it.
///
/// Scoped to one connection. A `u64` rather than a UUID because it costs four
/// bytes on the wire instead of thirty-eight, is trivial to generate in any
/// language, and needs no uniqueness beyond one socket.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RequestId(pub u64);

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Identity of the process on the other end of the socket, as far as the OS
/// will tell us.
///
/// This is diagnostic and audit information, **not** an authorisation
/// mechanism for anything that matters. The access control that matters is the
/// endpoint's DACL (Windows) or the socket's mode plus a `SO_PEERCRED` check
/// (unix), applied before a single byte is read. See
/// [`super::security`].
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct PeerIdentity {
    /// Process id of the peer, when the platform reports one.
    pub pid: Option<u32>,
    /// Effective user id of the peer. Unix only; Windows reports `None`
    /// because the named pipe's DACL, not a uid comparison, is the control.
    pub uid: Option<u32>,
    /// True when the transport positively established that the peer runs as
    /// the same user as the daemon. False means "not proven", not "hostile" —
    /// on Windows it is always false, and the DACL is what keeps strangers
    /// out.
    pub same_user: bool,
}

/// Everything a [`Handler`] method knows about the caller.
///
/// Passed by reference to every handler method so that the daemon can attribute
/// an action in the event log ("job started by pid 4123") without the protocol
/// having to carry a self-reported, forgeable identity field.
#[derive(Debug, Clone)]
pub struct RequestContext {
    /// Monotonic id of the connection within this daemon process.
    pub connection: u64,
    /// The request's own id, for correlating log lines with the client's view.
    pub request_id: RequestId,
    /// Protocol version this client negotiated.
    pub protocol: u32,
    /// Who is calling, as far as the OS reports.
    pub peer: PeerIdentity,
}

impl RequestContext {
    /// A context for in-process use — tests, and any future in-daemon caller
    /// that wants to reuse the dispatcher without a socket.
    pub fn local() -> RequestContext {
        RequestContext {
            connection: 0,
            request_id: RequestId(0),
            protocol: PROTOCOL_VERSION,
            peer: PeerIdentity { pid: Some(std::process::id()), uid: None, same_user: true },
        }
    }
}

// ===========================================================================
// Secret material on the wire
// ===========================================================================

/// A secret that arrives *from* a client — a passphrase, an access key.
///
/// Deserialising into this type rather than `String` is what keeps a
/// passphrase out of logs. The inner [`Secret`](crate::secret::Secret) zeroes
/// itself on drop and its `Debug` prints `Secret([redacted; N bytes])`, so
/// `format!("{request:?}")` — the thing a tracing span, a panic message or a
/// hasty `dbg!` actually does — cannot leak it. There is a test that asserts
/// exactly this.
///
/// ## What this does not fix, stated honestly
///
/// [`Request`] is an internally tagged enum, so serde buffers the object
/// before dispatching on `cmd`; the passphrase therefore exists briefly inside
/// serde's own buffer, and before that inside the socket read buffer. The read
/// buffer is zeroed by the transport after every frame
/// ([`super::codec`]); serde's is not reachable from here. That
/// residue is a deliberate, documented trade against a wire format that a
/// human can type. The mitigations that carry the weight are: the value never
/// lands in a `String` *field*, never appears in `Debug`, is never written to
/// the event log, and is never returned by any request.
///
/// ## Why it serialises at all
///
/// A client has to be able to *send* one. [`Serialize`] therefore emits the
/// plaintext. Nothing in the daemon ever serialises a [`Request`]; only
/// clients do, immediately before writing to the socket. Do not use this type
/// for anything the daemon sends.
#[derive(Clone, PartialEq, Eq)]
pub struct SecretString(crate::secret::Secret);

impl SecretString {
    /// Wrap an existing secret for transmission.
    pub fn new(secret: crate::secret::Secret) -> Self {
        SecretString(secret)
    }

    /// Build one from a string the caller already holds. The caller's copy is
    /// consumed and zeroed.
    pub fn from_string(s: String) -> Self {
        SecretString(crate::secret::Secret::from_string(s))
    }

    /// Unwrap into the core secret type, consuming the wrapper.
    pub fn into_secret(self) -> crate::secret::Secret {
        self.0
    }

    /// Borrow the secret. Deliberately named to make call sites auditable.
    pub fn expose(&self) -> &crate::secret::Secret {
        &self.0
    }
}

impl std::fmt::Debug for SecretString {
    /// Delegates to [`Secret`](crate::secret::Secret)'s redacting `Debug`.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Debug::fmt(&self.0, f)
    }
}

impl Serialize for SecretString {
    fn serialize<S: Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
        match self.0.expose_str() {
            Some(s) => serializer.serialize_str(s),
            // Non-UTF-8 key material cannot be a JSON string. Refusing is the
            // right outcome: silently emitting a lossy value would produce a
            // credential that does not work, diagnosed hours later.
            None => Err(serde::ser::Error::custom(
                "secret is not valid UTF-8 and cannot be sent as a JSON string",
            )),
        }
    }
}

impl<'de> Deserialize<'de> for SecretString {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> std::result::Result<Self, D::Error> {
        struct SecretVisitor;

        impl Visitor<'_> for SecretVisitor {
            type Value = SecretString;

            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str("a string containing secret material")
            }

            fn visit_str<E: de::Error>(self, v: &str) -> std::result::Result<Self::Value, E> {
                // Borrowed from the parser's buffer: copy the bytes straight
                // into the zeroing buffer without an intermediate `String`.
                Ok(SecretString(crate::secret::Secret::from_str(v)))
            }

            fn visit_string<E: de::Error>(self, v: String) -> std::result::Result<Self::Value, E> {
                // Owned: `from_string` takes the allocation over and zeroes
                // the caller's view of it.
                Ok(SecretString(crate::secret::Secret::from_string(v)))
            }
        }

        deserializer.deserialize_str(SecretVisitor)
    }
}

// ===========================================================================
// Supporting payload types
// ===========================================================================

/// What to do when a restored file already exists at the target path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConflictPolicy {
    /// Leave the existing file alone. The safe default: a restore should never
    /// destroy data the user did not ask it to destroy.
    #[default]
    Skip,
    /// Replace the existing file.
    Overwrite,
    /// Write the restored file next to the existing one with a suffix.
    KeepBoth,
    /// Abort the whole restore on the first collision.
    Fail,
}

/// A subscribable class of stream item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Topic {
    /// [`crate::state::Event`] — the activity log, as it is written.
    Events,
    /// Per-destination byte and file counters for running jobs. High volume;
    /// this is the topic a slow client will lag on.
    Progress,
    /// A whole [`StatusSnapshot`] whenever the aggregate picture changes
    /// (a run starts or ends, the vault locks, pause toggles). Low volume, and
    /// enough on its own to drive a tray icon.
    Status,
}

impl Topic {
    /// Every topic, for `subscribe` callers that want the firehose.
    pub fn all() -> Vec<Topic> {
        vec![Topic::Events, Topic::Progress, Topic::Status]
    }
}

/// One line of a `snapshot.browse` listing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnapshotEntry {
    /// File or directory name, not a full path.
    pub name: String,
    pub kind: EntryKind,
    pub size_bytes: u64,
    pub modified_at: Option<DateTime<Utc>>,
    /// Opaque kopia object id, used to descend or to restore just this entry.
    pub object_id: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EntryKind {
    File,
    Directory,
    Symlink,
}

/// One snapshot in a repository.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnapshotInfo {
    /// Kopia snapshot id. Opaque; pass it back verbatim.
    pub id: String,
    pub destination_id: Uuid,
    /// The job that created it, when superbackup created it.
    pub job_id: Option<Uuid>,
    pub created_at: DateTime<Utc>,
    /// Source path this snapshot covers.
    pub source_path: String,
    pub file_count: Option<u64>,
    pub total_bytes: Option<u64>,
    /// True for a snapshot kopia recorded as incomplete (a run that was
    /// interrupted). Restorable, but not a full point-in-time copy.
    pub incomplete: bool,
    #[serde(default)]
    pub tags: Vec<String>,
}

/// One diagnostic from `doctor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DoctorCheck {
    /// Stable identifier, e.g. `kopia.present`, `vault.readable`,
    /// `dest.reachable`. Branch on this, not on `title`.
    pub id: String,
    pub title: String,
    pub status: CheckStatus,
    /// Third-party detail; already scrubbed.
    pub detail: Option<String>,
    pub hint: Option<String>,
    /// True when `doctor` with `fix: true` can repair this automatically.
    pub fixable: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CheckStatus {
    Pass,
    Warn,
    Fail,
    /// Not applicable on this platform or in this configuration.
    Skipped,
}

/// A named thing referenced by another thing, for impact queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reference {
    pub id: Uuid,
    pub name: String,
}

/// One difference between the local configuration and the remote one.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfigChange {
    pub kind: ChangeKind,
    /// `job`, `destination`, `provider`, `project`, or `settings`.
    pub entity: String,
    pub id: Option<Uuid>,
    pub name: String,
    /// Human-readable one-liner. Already scrubbed.
    pub summary: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeKind {
    Added,
    Removed,
    Modified,
}

// ===========================================================================
// Errors on the wire
// ===========================================================================

/// A failure, in a form a caller can branch on.
///
/// `code` is the contract. `message` and `hint` are prose for a human and may
/// change between releases; `detail` is third-party output (kopia's stderr, a
/// git transport error) and is scrubbed before it is sent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorPayload {
    pub code: ErrorCode,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl ErrorPayload {
    /// Build a payload from a core error, scrubbing every string.
    pub fn from_error(error: &Error) -> ErrorPayload {
        ErrorPayload {
            code: error.code(),
            message: scrubbed(&error.to_string()),
            hint: error.hint().map(scrubbed),
            detail: None,
        }
    }

    /// Build a payload directly, for transport-level failures that have no
    /// [`Error`] behind them (a malformed line, a rate-limit rejection).
    pub fn new(code: ErrorCode, message: impl AsRef<str>) -> ErrorPayload {
        ErrorPayload { code, message: scrubbed(message.as_ref()), hint: None, detail: None }
    }

    /// Attach an actionable hint.
    pub fn with_hint(mut self, hint: impl AsRef<str>) -> ErrorPayload {
        self.hint = Some(scrubbed(hint.as_ref()));
        self
    }

    /// Attach scrubbed third-party detail.
    pub fn with_detail(mut self, detail: impl AsRef<str>) -> ErrorPayload {
        self.detail = Some(scrubbed(detail.as_ref()));
        self
    }

    /// Convert back into a core [`Error`], for a client that wants to bubble
    /// the daemon's failure through its own `Result` chain.
    ///
    /// The mapping is lossy on purpose: [`Error`] carries structured fields
    /// (`std::io::Error`, exit statuses) that do not survive JSON, so
    /// everything that is not a distinguished variant becomes the closest
    /// string-carrying one. `code` is preserved exactly, which is what callers
    /// are told to branch on.
    pub fn into_error(self) -> Error {
        match self.code {
            ErrorCode::Locked => Error::Locked,
            ErrorCode::BadPassphrase => Error::BadPassphrase,
            ErrorCode::KopiaMissing => Error::KopiaMissing,
            ErrorCode::DaemonUnreachable => Error::DaemonUnreachable,
            ErrorCode::Config => Error::Config(self.message),
            ErrorCode::VaultCorrupt => Error::VaultCorrupt(self.message),
            ErrorCode::Crypto => Error::Crypto(self.message),
            ErrorCode::RepoNotConnected => Error::RepoNotConnected(self.message),
            ErrorCode::RepoExists => Error::RepoExists(self.message),
            ErrorCode::Schedule => Error::Schedule(self.message),
            ErrorCode::JobNotFound => Error::JobNotFound(self.message),
            ErrorCode::JobRunning => Error::JobRunning(self.message),
            ErrorCode::JobCancelled => Error::JobCancelled(self.message),
            ErrorCode::Service => Error::Service(self.message),
            ErrorCode::Platform => Error::Platform(self.message),
            ErrorCode::Remote => Error::Remote(self.message),
            ErrorCode::Validation => Error::Validation(self.message),
            ErrorCode::Ipc => Error::Ipc(self.message),
            // `Io`, `VaultVersion`, `Kopia` and `Internal` carry fields that
            // cannot be reconstructed; keep the prose and the code.
            _ => Error::Internal(self.message),
        }
    }
}

/// Every [`ErrorCode`], for the schema. Kept as a list rather than derived
/// from the enum because `ErrorCode` lives in [`crate::error`], which this
/// module does not own; the test suite asserts the list stays complete by
/// round-tripping each name through serde.
pub(crate) const ERROR_CODES: &[&str] = &[
    "config",
    "io",
    "locked",
    "bad_passphrase",
    "vault_corrupt",
    "vault_version",
    "crypto",
    "kopia",
    "kopia_missing",
    "repo_not_connected",
    "repo_exists",
    "schedule",
    "job_not_found",
    "job_running",
    "job_cancelled",
    "ipc",
    "daemon_unreachable",
    "service",
    "platform",
    "remote",
    "validation",
    "internal",
];

fn scrubbed(s: &str) -> String {
    crate::redact::scrub(s).into_owned()
}

fn scrub_in_place(s: &mut String) {
    if let std::borrow::Cow::Owned(clean) = crate::redact::scrub(s) {
        *s = clean;
    }
}

fn scrub_opt(s: &mut Option<String>) {
    if let Some(v) = s {
        scrub_in_place(v);
    }
}

// ===========================================================================
// Streaming
// ===========================================================================

/// One item of a `subscribe` stream.
///
/// Delivered as `{"type":"stream","id":<subscription>,"body":{...}}` until the
/// client cancels or the connection closes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum StreamItem {
    /// A line was appended to the activity log.
    Event { event: Box<Event> },
    /// Counters moved for one destination of one running job.
    Progress {
        run_id: Uuid,
        job_id: Uuid,
        destination_id: Uuid,
        status: RunStatus,
        progress: Box<Progress>,
    },
    /// The aggregate picture changed.
    Status { snapshot: Box<StatusSnapshot> },
    /// **Backpressure marker.** The subscriber did not read fast enough and
    /// the daemon dropped the oldest `missed` items rather than buffering them
    /// or stalling the engine that produces them.
    ///
    /// The correct reaction is not to try to recover the lost items — they are
    /// gone — but to resynchronise: issue `status` and redraw from the
    /// snapshot. A client that renders a log tail should show a gap marker.
    Lagged { missed: u64 },
}

impl StreamItem {
    /// The topic this item belongs to, used to filter per subscription.
    ///
    /// [`StreamItem::Lagged`] deliberately has no topic of its own: it is
    /// delivered to whichever subscription lagged, regardless of what that
    /// subscription asked for, because suppressing it would leave a client
    /// silently showing stale data.
    pub fn topic(&self) -> Option<Topic> {
        match self {
            StreamItem::Event { .. } => Some(Topic::Events),
            StreamItem::Progress { .. } => Some(Topic::Progress),
            StreamItem::Status { .. } => Some(Topic::Status),
            StreamItem::Lagged { .. } => None,
        }
    }

    /// True when a subscription for `topics` should receive this item.
    pub fn matches(&self, topics: &[Topic]) -> bool {
        match self.topic() {
            None => true,
            Some(t) => topics.contains(&t),
        }
    }

    fn sanitise(&mut self) {
        match self {
            StreamItem::Event { event } => {
                scrub_in_place(&mut event.message);
            }
            StreamItem::Progress { progress, .. } => {
                scrub_opt(&mut progress.current_path);
            }
            StreamItem::Status { snapshot } => {
                for run in &mut snapshot.active_runs {
                    sanitise_run(run);
                }
                for event in &mut snapshot.recent_events {
                    scrub_in_place(&mut event.message);
                }
            }
            StreamItem::Lagged { .. } => {}
        }
    }
}

fn sanitise_run(run: &mut JobRun) {
    for dest in &mut run.destinations {
        scrub_opt(&mut dest.progress.current_path);
        for warning in &mut dest.warnings {
            scrub_in_place(warning);
        }
        if let Some(err) = &mut dest.error {
            scrub_in_place(&mut err.message);
            scrub_opt(&mut err.hint);
            scrub_opt(&mut err.detail);
        }
    }
}

// ===========================================================================
// Reply payloads
// ===========================================================================

/// Success with no payload. Serialised as `{"reply":"ack"}`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AckReply {}

/// A whole [`StatusSnapshot`] — the payload behind the tray icon, the
/// dashboard and `superbackup status --json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StatusReply {
    pub snapshot: Box<StatusSnapshot>,
}

/// Build and protocol identity, for compatibility checks and bug reports.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VersionReply {
    pub version: String,
    pub protocol: u32,
    pub min_protocol: u32,
    pub target_os: String,
    pub target_arch: String,
    pub kopia_version: Option<String>,
    /// True when this daemon is the machine-wide service instance rather than
    /// a per-user tray.
    pub service_scope: bool,
}

/// The one value that drives the tray icon, plus why.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthReply {
    pub health: Health,
    /// One line suitable for a tooltip.
    pub summary: String,
    /// Specific reasons behind anything worse than `Idle`, so a caller does
    /// not have to fetch the whole snapshot to explain the icon.
    #[serde(default)]
    pub reasons: Vec<String>,
}

/// Diagnostics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DoctorReply {
    /// True when no check failed. Warnings do not clear this flag to false.
    pub ok: bool,
    pub checks: Vec<DoctorCheck>,
    /// Checks that `doctor` repaired during this call, when `fix` was set.
    #[serde(default)]
    pub fixed: Vec<String>,
}

/// The full command surface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaReply {
    pub schema: Box<Schema>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobsReply {
    pub jobs: Vec<Job>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobReply {
    pub job: Box<Job>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunsReply {
    pub runs: Vec<JobRun>,
}

/// Something was accepted for execution. The work happens asynchronously;
/// follow it with `subscribe` or poll `status`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartedReply {
    pub run_id: Uuid,
    /// False when the run was queued behind another rather than started
    /// immediately (`max_parallel_jobs`).
    pub started: bool,
    /// Why it was queued, skipped or degraded — metered connection, on
    /// battery, dry run.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

/// Runs that were asked to stop. Empty when nothing was running, which is a
/// success, not an error: `stop` is idempotent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoppedReply {
    pub stopped: Vec<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DestinationsReply {
    pub destinations: Vec<Destination>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DestinationReply {
    pub destination: Box<Destination>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvidersReply {
    pub providers: Vec<StorageProvider>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderReply {
    pub provider: Box<StorageProvider>,
}

/// Outcome of a connectivity test.
///
/// A failed probe is a *successful* request with `reachable: false` — the
/// daemon answered the question it was asked. An error response means the
/// question could not be asked at all (no such destination, vault locked).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeReply {
    pub reachable: bool,
    /// True when a write probe succeeded, not merely a read. A destination
    /// that is readable but not writable will fail every backup, and finding
    /// that out at 2am is the failure mode this field exists to prevent.
    pub writable: bool,
    pub latency_ms: Option<u64>,
    /// Scrubbed transport detail, present mostly when `reachable` is false.
    pub detail: Option<String>,
}

/// State of the kopia repository behind a destination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepositoryReply {
    pub destination_id: Uuid,
    pub connected: bool,
    /// Kopia's unique id for the repository, once connected.
    pub repository_id: Option<String>,
    /// True when this call created the repository rather than connecting to
    /// an existing one.
    pub created: bool,
}

/// Space accounting for one destination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorageStatsReply {
    pub destination_id: Uuid,
    pub snapshot_count: u64,
    /// Logical size of everything stored, before dedup and compression.
    pub logical_bytes: Option<u64>,
    /// Bytes actually occupied at the destination — the number that maps to a
    /// storage bill.
    pub stored_bytes: Option<u64>,
    pub last_snapshot_at: Option<DateTime<Utc>>,
    /// When the figures were computed. Stats can be expensive, so they may be
    /// served from cache unless `refresh` was set.
    pub computed_at: DateTime<Utc>,
}

/// What would break if this provider were deleted or its keys rotated.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsedByReply {
    pub destinations: Vec<Reference>,
    pub jobs: Vec<Reference>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnapshotsReply {
    pub snapshots: Vec<SnapshotInfo>,
}

/// One directory level of a snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListingReply {
    /// The path that was listed, normalised, `/`-separated, `""` for the root.
    pub path: String,
    pub entries: Vec<SnapshotEntry>,
    /// True when the directory has more entries than the daemon is willing to
    /// serialise in one response. Descend or filter rather than expecting the
    /// rest.
    pub truncated: bool,
}

/// Vault state. Returned by `vault.unlock`, `vault.lock` and
/// `vault.is_unlocked` alike so a caller has one shape to handle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnlockedReply {
    pub unlocked: bool,
    /// When the vault will auto-lock, if `auto_lock_minutes` is non-zero.
    pub auto_lock_at: Option<DateTime<Utc>>,
}

/// The *names* of the secrets in the vault. Never the values — see the module
/// documentation on why there is no `GetSecret`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretRefsReply {
    pub refs: Vec<SecretRef>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PauseReply {
    pub pause: crate::model::PauseState,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BandwidthReply {
    pub bandwidth: BandwidthSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SettingsReply {
    pub settings: Box<Settings>,
}

/// State of the remote configuration repository.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemoteStatusReply {
    /// `None` when no remote is configured.
    pub url: Option<String>,
    pub branch: Option<String>,
    pub last_pull_at: Option<DateTime<Utc>>,
    pub last_known_commit: Option<String>,
    /// True when the local configuration differs from the last pulled remote.
    pub local_changes: bool,
    /// True when the remote has commits the local clone has not applied.
    pub remote_changes: bool,
    /// Scrubbed transport detail (a git message).
    pub detail: Option<String>,
}

/// What a `remote.apply` would change.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemoteDiffReply {
    pub changes: Vec<ConfigChange>,
    pub remote_commit: Option<String>,
}

/// Service installation and autostart state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceReply {
    pub installed: bool,
    pub running: bool,
    /// Whether the *user-mode* application starts at login. Independent of the
    /// service: a machine can have both, either, or neither.
    pub autostart: bool,
    /// `user` or `system`.
    pub scope: String,
    pub detail: Option<String>,
}

/// A subscription was opened. Stream items follow on the same `id` until the
/// client sends `{"type":"cancel","id":N}` or closes the connection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscribedReply {
    pub subscription: RequestId,
    /// The topics actually subscribed, after normalisation.
    pub topics: Vec<Topic>,
}

// ===========================================================================
// The Reply enum, generated so its tags cannot drift from the schema
// ===========================================================================

macro_rules! replies {
    ($( $wire:literal $variant:ident($payload:ty) $doc:literal )*) => {
        /// A successful response payload.
        ///
        /// Internally tagged: the `reply` key names the shape, and the
        /// payload struct's fields sit alongside it. Which tag a command
        /// produces is fixed and published in
        /// [`CommandSpec::reply`](super::CommandSpec::reply), so a caller can
        /// deserialise straight into the expected struct and treat anything
        /// else as a protocol violation.
        #[derive(Debug, Clone, Serialize, Deserialize)]
        #[serde(tag = "reply")]
        pub enum Reply {
            $(
                #[doc = $doc]
                #[serde(rename = $wire)]
                $variant($payload),
            )*
        }

        impl Reply {
            /// The `reply` discriminator this value serialises with.
            pub fn tag(&self) -> &'static str {
                match self { $( Reply::$variant(_) => $wire, )* }
            }
        }

        /// Compile-time map from a [`Reply`] variant to its wire tag.
        ///
        /// The command table refers to `reply_tag::Started` rather than to the
        /// string `"started"`, so the schema's `reply` field and the enum's
        /// serde rename are the same token. Renaming one without the other is
        /// a compile error.
        #[doc(hidden)]
        #[allow(non_upper_case_globals)]
        pub mod reply_tag {
            $( pub const $variant: &str = $wire; )*
        }

        fn reply_specs() -> Vec<ReplySpec> {
            vec![ $( ReplySpec {
                name: $wire.to_string(),
                payload: stringify!($payload).to_string(),
                summary: $doc.trim().to_string(),
            }, )* ]
        }
    };
}

replies! {
    "ack" Ack(AckReply)
        "The command succeeded and has no payload."
    "status" Status(StatusReply)
        "A full runtime snapshot."
    "version" Version(VersionReply)
        "Build and protocol identity."
    "health" Health(HealthReply)
        "The aggregate health value and why it is what it is."
    "doctor" Doctor(DoctorReply)
        "Diagnostic check results."
    "schema" Schema(SchemaReply)
        "The full machine-readable command surface."
    "jobs" Jobs(JobsReply)
        "A list of jobs."
    "job" Job(JobReply)
        "One job."
    "runs" Runs(RunsReply)
        "A list of job runs, newest first."
    "started" Started(StartedReply)
        "Work was accepted; follow it with subscribe or status."
    "stopped" Stopped(StoppedReply)
        "The runs that were asked to stop."
    "destinations" Destinations(DestinationsReply)
        "A list of destinations."
    "destination" Destination(DestinationReply)
        "One destination."
    "providers" Providers(ProvidersReply)
        "A list of storage providers."
    "provider" Provider(ProviderReply)
        "One storage provider."
    "probe" Probe(ProbeReply)
        "The outcome of a connectivity test."
    "repository" Repository(RepositoryReply)
        "The state of a destination's kopia repository."
    "storage_stats" StorageStats(StorageStatsReply)
        "Space accounting for one destination."
    "used_by" UsedBy(UsedByReply)
        "What references the queried entity."
    "snapshots" Snapshots(SnapshotsReply)
        "A list of snapshots."
    "listing" Listing(ListingReply)
        "One directory level inside a snapshot."
    "unlocked" Unlocked(UnlockedReply)
        "Vault lock state."
    "secret_refs" SecretRefs(SecretRefsReply)
        "The names of the secrets in the vault, never their values."
    "pause" Pause(PauseReply)
        "Global pause state."
    "bandwidth" Bandwidth(BandwidthReply)
        "The effective bandwidth ceiling."
    "settings" Settings(SettingsReply)
        "Application settings."
    "remote_status" RemoteStatus(RemoteStatusReply)
        "State of the remote configuration repository."
    "remote_diff" RemoteDiff(RemoteDiffReply)
        "What applying the remote configuration would change."
    "service" Service(ServiceReply)
        "Service installation and autostart state."
    "subscribed" Subscribed(SubscribedReply)
        "A stream was opened on this request id."
}

impl Reply {
    /// Scrub every field that can carry third-party text.
    ///
    /// Called by the transport on the way out, so a handler cannot forget.
    pub fn sanitise(&mut self) {
        match self {
            Reply::Status(r) => {
                for run in &mut r.snapshot.active_runs {
                    sanitise_run(run);
                }
                for event in &mut r.snapshot.recent_events {
                    scrub_in_place(&mut event.message);
                }
            }
            Reply::Health(r) => {
                scrub_in_place(&mut r.summary);
                for reason in &mut r.reasons {
                    scrub_in_place(reason);
                }
            }
            Reply::Doctor(r) => {
                for check in &mut r.checks {
                    scrub_opt(&mut check.detail);
                    scrub_opt(&mut check.hint);
                }
            }
            Reply::Runs(r) => {
                for run in &mut r.runs {
                    sanitise_run(run);
                }
            }
            Reply::Started(r) => scrub_opt(&mut r.note),
            Reply::Probe(r) => scrub_opt(&mut r.detail),
            Reply::RemoteStatus(r) => {
                scrub_opt(&mut r.detail);
                scrub_opt(&mut r.url);
            }
            Reply::RemoteDiff(r) => {
                for change in &mut r.changes {
                    scrub_in_place(&mut change.summary);
                }
            }
            Reply::Service(r) => scrub_opt(&mut r.detail),
            // The rest carry only values this process authored: ids, counts,
            // timestamps, and configuration the user typed themselves.
            _ => {}
        }
    }
}

// ===========================================================================
// Command flags
// ===========================================================================

/// Behavioural flags published in the schema.
///
/// Referred to by identifier from the command table, so a typo is a compile
/// error rather than a silently wrong schema.
#[doc(hidden)]
#[allow(non_upper_case_globals)]
pub mod flag {
    /// Changes persistent state — configuration, the vault, or the
    /// repository. A read-only client (a dashboard, a cautious agent) should
    /// refuse to issue these.
    pub const mutating: &str = "mutating";

    /// Fails with [`ErrorCode::Locked`](crate::error::ErrorCode::Locked)
    /// while the vault is locked, because it needs a secret the vault holds.
    /// Unlock first with `vault.unlock`.
    pub const needs_unlock: &str = "needs_unlock";

    /// Causes the daemon to act with whatever privilege it happens to be
    /// running as, which for the service instance is SYSTEM or root.
    ///
    /// Every command carrying this flag must be authorised by something the
    /// caller *knows* (the vault passphrase) or by a policy the daemon holds,
    /// never by the caller's identity alone — the endpoint's access control
    /// establishes only that the peer is a local user, not that the peer is
    /// entitled to act as SYSTEM. Concretely: nothing here takes a path or a
    /// command line from the caller and executes it with elevated privilege;
    /// paths come from the stored configuration, and changing that
    /// configuration is itself gated.
    pub const elevated: &str = "elevated";

    /// Opens a stream on the request id instead of producing a single
    /// response. Handled by the transport, not by a [`Handler`](super::Handler)
    /// method.
    pub const streaming: &str = "streaming";
}

// ===========================================================================
// The command table
// ===========================================================================

/// Generates, from one table:
///
/// 1. the [`Request`] enum and its serde representation,
/// 2. [`Request::command`],
/// 3. the [`Handler`] trait the daemon implements,
/// 4. [`dispatch`], which routes a request to a handler method, and
/// 5. the machine-readable [`Schema`].
///
/// Because all five come from the same tokens, they cannot disagree. Adding a
/// command is a five-line edit in one place; forgetting to wire it up anywhere
/// is impossible.
///
/// Two sections:
///
/// * `dispatched` — commands the daemon answers. Each names the [`Handler`]
///   method it routes to.
/// * `manual` — commands the *transport* answers without troubling the
///   daemon: `schema`, which is generated in-process, and `subscribe`, which
///   is a stream rather than a response. They still appear in [`Request`] and
///   in the schema; they simply have no handler method.
macro_rules! protocol {
    (
        dispatched {
            $(
                $wire:literal $variant:ident => $method:ident -> $rvar:ident($rty:ty)
                flags [$($flag:ident),* $(,)?]
                doc $doc:literal
                params { $( $pname:ident : $pty:ty = $pdoc:literal ),* $(,)? }
            )*
        }
        manual {
            $(
                $mwire:literal $mvariant:ident -> $mrvar:ident
                flags [$($mflag:ident),* $(,)?]
                doc $mdoc:literal
                params { $( $mpname:ident : $mpty:ty = $mpdoc:literal ),* $(,)? }
            )*
        }
    ) => {
        /// Everything a client can ask the daemon to do.
        ///
        /// Internally tagged on `cmd`, with parameters flat alongside it:
        /// `{"cmd":"job.run","job":"docs","dry_run":false}`.
        ///
        /// `Debug` is safe to log: secret parameters are
        /// [`SecretString`], whose `Debug` redacts.
        #[derive(Debug, Clone, Serialize, Deserialize)]
        #[serde(tag = "cmd")]
        pub enum Request {
            $(
                #[doc = $doc]
                #[serde(rename = $wire)]
                $variant { $( #[doc = $pdoc] $pname: $pty, )* },
            )*
            $(
                #[doc = $mdoc]
                #[serde(rename = $mwire)]
                $mvariant { $( #[doc = $mpdoc] $mpname: $mpty, )* },
            )*
        }

        impl Request {
            /// The wire value of this request's `cmd` field.
            ///
            /// Useful for logging and for correlating a request with its
            /// [`CommandSpec`].
            pub fn command(&self) -> &'static str {
                match self {
                    $( Request::$variant { .. } => $wire, )*
                    $( Request::$mvariant { .. } => $mwire, )*
                }
            }

            /// The specification for this request's command.
            ///
            /// Builds the whole schema and searches it, so this is for
            /// diagnostics and for a CLI's help output, not for a hot path.
            /// `None` is unreachable in practice and would mean the generated
            /// schema had lost a command it also generated.
            pub fn spec(&self) -> Option<CommandSpec> {
                let name = self.command();
                commands().into_iter().find(|c| c.name == name)
            }
        }

        /// What the daemon implements to serve IPC.
        ///
        /// One method per command, generated from the same table as
        /// [`Request`], so a new command is a compile error until the daemon
        /// handles it. That is the point: an IPC surface that silently answers
        /// `unimplemented` is worse than one that will not build.
        ///
        /// Deliberately expressed in terms of [`crate::model`],
        /// [`crate::state`] and this module's own types only. The engine, the
        /// kopia driver, the vault and the configuration loader are *not*
        /// referenced, so the transport compiles and is testable
        /// independently of them.
        ///
        /// Methods return [`Result`]; an `Err` becomes an `error` frame with
        /// the error's [`ErrorCode`]. Returning an error is the normal way to
        /// refuse — panicking is not, and the transport treats a panicking
        /// handler as a failed request rather than letting it take the daemon
        /// down.
        ///
        /// ## Running as a service
        ///
        /// The daemon may run as SYSTEM or root while its clients are
        /// unprivileged. Implementations must therefore authorise on what the
        /// caller *knows*, not on the fact that it reached the socket:
        /// anything touching secrets requires an unlocked vault, and the vault
        /// is unlocked only by presenting the passphrase. Commands whose
        /// schema entry carries the `elevated` flag are the ones where this
        /// matters most.
        #[allow(clippy::too_many_arguments)]
        pub trait Handler: Send + Sync + 'static {
            $(
                #[doc = $doc]
                $(
                    #[doc = ""]
                    #[doc = concat!("* `", stringify!($pname), "` — ", $pdoc)]
                )*
                fn $method(
                    &self,
                    ctx: &RequestContext,
                    $( $pname: $pty, )*
                ) -> impl ::std::future::Future<Output = Result<$rty>> + Send;
            )*

            /// The daemon's event fan-out, one receiver per subscription.
            ///
            /// Not generated from the command table because `subscribe` is a
            /// stream rather than a request/response pair.
            ///
            /// Must be a *broadcast* channel: it gives drop-oldest semantics
            /// for free, which is exactly the required backpressure policy. A
            /// subscriber that falls behind sees
            /// [`RecvError::Lagged`](tokio::sync::broadcast::error::RecvError::Lagged),
            /// which the transport turns into
            /// [`StreamItem::Lagged`]. Producing an item must never block on
            /// a slow consumer, and with `broadcast::Sender::send` it does
            /// not.
            fn event_stream(
                &self,
                ctx: &RequestContext,
                topics: &[Topic],
            ) -> Result<::tokio::sync::broadcast::Receiver<StreamItem>>;
        }

        /// Route one request to the handler method the table names for it.
        ///
        /// The `manual` commands never reach here; the transport intercepts
        /// them. Reaching this arm means the transport has a bug, so it
        /// reports one rather than pretending.
        pub async fn dispatch<H: Handler>(
            handler: &H,
            ctx: &RequestContext,
            request: Request,
        ) -> Result<Reply> {
            match request {
                $(
                    Request::$variant { $( $pname, )* } => handler
                        .$method(ctx, $( $pname, )*)
                        .await
                        .map(Reply::$rvar),
                )*
                $(
                    Request::$mvariant { .. } => Err(Error::Ipc(format!(
                        "`{}` is answered by the IPC transport and must not reach the dispatcher",
                        $mwire
                    ))),
                )*
            }
        }

        /// Every command, in table order.
        pub fn commands() -> Vec<CommandSpec> {
            vec![
                $(
                    CommandSpec {
                        name: $wire.to_string(),
                        summary: $doc.trim().to_string(),
                        params: vec![ $( param(stringify!($pname), stringify!($pty), $pdoc) ),* ],
                        reply: reply_tag::$rvar.to_string(),
                        flags: vec![ $( flag::$flag.to_string() ),* ],
                    },
                )*
                $(
                    CommandSpec {
                        name: $mwire.to_string(),
                        summary: $mdoc.trim().to_string(),
                        params: vec![ $( param(stringify!($mpname), stringify!($mpty), $mpdoc) ),* ],
                        reply: reply_tag::$mrvar.to_string(),
                        flags: vec![ $( flag::$mflag.to_string() ),* ],
                    },
                )*
            ]
        }
    };
}

protocol! {
    dispatched {
        // -------------------------------------------------------------- status
        "ping" Ping => ping -> Ack(AckReply)
            flags []
            doc "Liveness probe. Cheapest possible round trip; does no work and takes no locks."
            params {}

        "status" Status => status -> Status(StatusReply)
            flags []
            doc "Everything the tray, the dashboard and `superbackup status` need, in one message."
            params {}

        "version" Version => version -> Version(VersionReply)
            flags []
            doc "Build version, protocol range, platform and kopia version."
            params {}

        "health" Health => health -> Health(HealthReply)
            flags []
            doc "Just the aggregate health value and the reasons behind it, for a tray tooltip."
            params {}

        "doctor" Doctor => doctor -> Doctor(DoctorReply)
            flags [elevated]
            doc "Run every self-check: kopia present, vault readable, destinations reachable, service healthy."
            params {
                fix: bool = "Attempt the repairs that are marked fixable, instead of only reporting them.",
            }

        // ---------------------------------------------------------------- jobs
        "job.list" JobList => list_jobs -> Jobs(JobsReply)
            flags []
            doc "List backup jobs."
            params {
                include_disabled: bool = "Include jobs the user has switched off.",
            }

        "job.get" JobGet => get_job -> Job(JobReply)
            flags []
            doc "Fetch one job by id, or by a unique prefix of its name."
            params {
                job: String = "Job id, or a unique prefix of the job's name.",
            }

        "job.create" JobCreate => create_job -> Job(JobReply)
            flags [mutating]
            doc "Create a job. The daemon assigns the id and rejects an id that already exists."
            params {
                job: Box<Job> = "The job to create. Its `id` is ignored and replaced.",
            }

        "job.update" JobUpdate => update_job -> Job(JobReply)
            flags [mutating]
            doc "Replace a job wholesale. Not a patch: send the complete object from `job.get`."
            params {
                job: Box<Job> = "The job to store, identified by its `id`.",
            }

        "job.delete" JobDelete => delete_job -> Ack(AckReply)
            flags [mutating]
            doc "Delete a job. Does not delete any snapshot it created; data outlives configuration."
            params {
                job: String = "Job id, or a unique prefix of the job's name.",
            }

        "job.set_enabled" JobSetEnabled => set_job_enabled -> Job(JobReply)
            flags [mutating]
            doc "Enable or disable a job's schedule without deleting it."
            params {
                job: String = "Job id, or a unique prefix of the job's name.",
                enabled: bool = "True to let the schedule fire, false to suspend it.",
            }

        "job.run" JobRun => run_job -> Started(StartedReply)
            flags [mutating, needs_unlock, elevated]
            doc "Start a job now, outside its schedule. Returns as soon as the run is accepted."
            params {
                job: String = "Job id, or a unique prefix of the job's name.",
                dry_run: bool = "Report what would be copied without writing anything to any destination.",
            }

        "job.stop" JobStop => stop_run -> Stopped(StoppedReply)
            flags [mutating]
            doc "Cancel one in-flight run. Idempotent: stopping a finished run is not an error."
            params {
                run_id: Uuid = "The run to cancel, from `status` or a progress stream item.",
            }

        "job.stop_all" JobStopAll => stop_all_runs -> Stopped(StoppedReply)
            flags [mutating]
            doc "Cancel every in-flight run. Used by shutdown and by the tray's panic button."
            params {}

        "job.history" JobHistory => job_history -> Runs(RunsReply)
            flags []
            doc "Completed runs, newest first, from the bounded local history."
            params {
                job: Option<String> = "Restrict to one job; omit for every job.",
                limit: u32 = "Maximum runs to return. The daemon caps this at its own history size.",
            }

        // -------------------------------------------------------- destinations
        "dest.list" DestinationList => list_destinations -> Destinations(DestinationsReply)
            flags []
            doc "List destinations."
            params {}

        "dest.get" DestinationGet => get_destination -> Destination(DestinationReply)
            flags []
            doc "Fetch one destination by id, or by a unique prefix of its name."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
            }

        "dest.create" DestinationCreate => create_destination -> Destination(DestinationReply)
            flags [mutating]
            doc "Create a destination. Does not create the repository; call `dest.repo_create` next."
            params {
                destination: Box<Destination> = "The destination to create. Its `id` is ignored and replaced.",
            }

        "dest.update" DestinationUpdate => update_destination -> Destination(DestinationReply)
            flags [mutating]
            doc "Replace a destination wholesale."
            params {
                destination: Box<Destination> = "The destination to store, identified by its `id`.",
            }

        "dest.delete" DestinationDelete => delete_destination -> Ack(AckReply)
            flags [mutating]
            doc "Remove a destination from the configuration. Never deletes stored backup data."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                force: bool = "Delete even though jobs still reference it; those jobs lose the destination.",
            }

        "dest.test" DestinationTest => test_destination -> Probe(ProbeReply)
            flags [needs_unlock, elevated]
            doc "Check that the destination is reachable and writable, without touching any repository."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
            }

        "dest.repo_create" DestinationRepoCreate => create_repository -> Repository(RepositoryReply)
            flags [mutating, needs_unlock, elevated]
            doc "Create a kopia repository at the destination and connect to it."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                encryption: Option<EncryptionSettings> = "Algorithms to create the repository with; omit for the recommended defaults.",
            }

        "dest.repo_connect" DestinationRepoConnect => connect_repository -> Repository(RepositoryReply)
            flags [mutating, needs_unlock, elevated]
            doc "Connect to a repository that already exists at the destination."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
            }

        "dest.repo_disconnect" DestinationRepoDisconnect => disconnect_repository -> Repository(RepositoryReply)
            flags [mutating]
            doc "Drop the local connection to a repository. The repository and its data are untouched."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
            }

        "dest.stats" DestinationStats => destination_stats -> StorageStats(StorageStatsReply)
            flags [needs_unlock, elevated]
            doc "Snapshot count and space used at a destination."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                refresh: bool = "Recompute rather than serving cached figures. Can be slow on a remote repository.",
            }

        // ----------------------------------------------------------- providers
        "provider.list" ProviderList => list_providers -> Providers(ProvidersReply)
            flags []
            doc "List storage providers. Credentials appear only as vault handles, never as values."
            params {}

        "provider.get" ProviderGet => get_provider -> Provider(ProviderReply)
            flags []
            doc "Fetch one provider by id, or by a unique prefix of its name."
            params {
                provider: String = "Provider id, or a unique prefix of its name.",
            }

        "provider.create" ProviderCreate => create_provider -> Provider(ProviderReply)
            flags [mutating]
            doc "Create a provider. Store its credentials separately with `vault.set_secret`."
            params {
                provider: Box<StorageProvider> = "The provider to create. Its `id` is ignored and replaced.",
            }

        "provider.update" ProviderUpdate => update_provider -> Provider(ProviderReply)
            flags [mutating]
            doc "Replace a provider wholesale."
            params {
                provider: Box<StorageProvider> = "The provider to store, identified by its `id`.",
            }

        "provider.delete" ProviderDelete => delete_provider -> Ack(AckReply)
            flags [mutating]
            doc "Delete a provider and forget its vault secrets. Check `provider.used_by` first."
            params {
                provider: String = "Provider id, or a unique prefix of its name.",
                force: bool = "Delete even though destinations still reference it.",
            }

        "provider.test" ProviderTest => test_provider -> Probe(ProbeReply)
            flags [needs_unlock, elevated]
            doc "Check that the provider's endpoint answers and its credentials are accepted."
            params {
                provider: String = "Provider id, or a unique prefix of its name.",
            }

        "provider.used_by" ProviderUsedBy => provider_used_by -> UsedBy(UsedByReply)
            flags []
            doc "What would break if this provider were deleted or its keys rotated."
            params {
                provider: String = "Provider id, or a unique prefix of its name.",
            }

        "provider.rotate_credentials" ProviderRotateCredentials => rotate_provider_credentials -> Provider(ProviderReply)
            flags [mutating, needs_unlock]
            doc "Replace a provider's stored credentials. Affects every destination that inherits them."
            params {
                provider: String = "Provider id, or a unique prefix of its name.",
                access_key_id: SecretString = "New access key id.",
                secret_access_key: SecretString = "New secret access key.",
                session_token: Option<SecretString> = "New session token, for temporary credentials.",
            }

        // ------------------------------------------------- snapshots / restore
        "snapshot.list" SnapshotList => list_snapshots -> Snapshots(SnapshotsReply)
            flags [needs_unlock, elevated]
            doc "List snapshots held at a destination, newest first."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                job: Option<String> = "Restrict to snapshots created by one job.",
                limit: u32 = "Maximum snapshots to return; 0 means the daemon's own cap.",
            }

        "snapshot.browse" SnapshotBrowse => browse_snapshot -> Listing(ListingReply)
            flags [needs_unlock, elevated]
            doc "List one directory level inside a snapshot, for a restore browser."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                snapshot: String = "Snapshot id from `snapshot.list`.",
                path: String = "Directory to list, `/`-separated, empty for the snapshot root.",
            }

        "snapshot.restore" SnapshotRestore => restore_snapshot -> Started(StartedReply)
            flags [mutating, needs_unlock, elevated]
            doc "Restore a path out of a snapshot to a target directory. Returns as soon as it is accepted."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                snapshot: String = "Snapshot id from `snapshot.list`.",
                path: String = "Path inside the snapshot, empty for everything.",
                target: PathBuf = "Directory on this machine to restore into. Must be absolute.",
                conflict: ConflictPolicy = "What to do when a file already exists at the target.",
                dry_run: bool = "Report what would be written without writing it.",
            }

        "snapshot.delete" SnapshotDelete => delete_snapshot -> Ack(AckReply)
            flags [mutating, needs_unlock, elevated]
            doc "Delete one snapshot. Space is reclaimed at the next maintenance run, not immediately."
            params {
                destination: String = "Destination id, or a unique prefix of its name.",
                snapshot: String = "Snapshot id from `snapshot.list`.",
            }

        // --------------------------------------------------------------- vault
        "vault.unlock" VaultUnlock => unlock_vault -> Unlocked(UnlockedReply)
            flags [mutating]
            doc "Unlock the vault with the master passphrase, so scheduled runs and remote destinations can work."
            params {
                passphrase: SecretString = "The master passphrase. Never logged, never echoed, never returned.",
            }

        "vault.lock" VaultLock => lock_vault -> Unlocked(UnlockedReply)
            flags [mutating]
            doc "Forget the derived keys. Scheduled runs that need a secret will be skipped until the next unlock."
            params {}

        "vault.is_unlocked" VaultIsUnlocked => vault_is_unlocked -> Unlocked(UnlockedReply)
            flags []
            doc "Whether the vault is currently unlocked, and when it will auto-lock."
            params {}

        "vault.change_passphrase" VaultChangePassphrase => change_passphrase -> Ack(AckReply)
            flags [mutating, needs_unlock]
            doc "Re-seal the vault under a new master passphrase. Every stored secret is preserved."
            params {
                current: SecretString = "The current master passphrase, verified before anything is written.",
                replacement: SecretString = "The new master passphrase. There is no recovery if it is lost.",
            }

        "vault.set_secret" VaultSetSecret => set_secret -> Ack(AckReply)
            flags [mutating, needs_unlock]
            doc "Store or replace one secret under a handle that the configuration refers to."
            params {
                secret_ref: SecretRef = "The handle, e.g. `s3-access-key:<provider-uuid>`.",
                value: SecretString = "The secret. This is a one-way door: there is no request that reads it back.",
            }

        "vault.list_refs" VaultListRefs => list_secret_refs -> SecretRefs(SecretRefsReply)
            flags [needs_unlock]
            doc "List the handles the vault holds, so the GUI can show which credentials are set. Values are never returned."
            params {}

        // ------------------------------------------------------------- control
        "control.pause" ControlPause => pause -> Pause(PauseReply)
            flags [mutating]
            doc "Suspend all scheduled runs, optionally for a fixed period."
            params {
                seconds: Option<u64> = "How long to stay paused; omit to pause until explicitly resumed.",
                reason: Option<String> = "Shown in the tray so the user cannot forget why backups are off.",
            }

        "control.resume" ControlResume => resume -> Pause(PauseReply)
            flags [mutating]
            doc "Lift a pause and let schedules fire again."
            params {}

        "control.pause_state" ControlPauseState => pause_state -> Pause(PauseReply)
            flags []
            doc "Whether backups are paused, and until when."
            params {}

        "control.set_bandwidth" ControlSetBandwidth => set_bandwidth -> Bandwidth(BandwidthReply)
            flags [mutating]
            doc "Set the global bandwidth ceiling. Applies to runs started after this call."
            params {
                bandwidth: BandwidthSettings = "The new ceiling. Null rates mean unlimited.",
            }

        "control.reload_config" ControlReloadConfig => reload_config -> Ack(AckReply)
            flags [mutating]
            doc "Re-read configuration from disk, for a user who edited it by hand."
            params {}

        "control.shutdown" ControlShutdown => shutdown -> Ack(AckReply)
            flags [mutating, elevated]
            doc "Stop the daemon gracefully. In-flight runs are cancelled and recorded as cancelled, not failed."
            params {
                stop_runs: bool = "Cancel in-flight runs immediately instead of waiting for them to finish.",
            }

        // ------------------------------------------------------------ settings
        "settings.get" SettingsGet => get_settings -> Settings(SettingsReply)
            flags []
            doc "Read application settings."
            params {}

        "settings.update" SettingsUpdate => update_settings -> Settings(SettingsReply)
            flags [mutating]
            doc "Replace application settings wholesale. Not a patch."
            params {
                settings: Box<Settings> = "The complete settings object, as returned by `settings.get`.",
            }

        // ------------------------------------------------------- remote config
        "remote.pull" RemotePull => remote_pull -> RemoteStatus(RemoteStatusReply)
            flags [needs_unlock, elevated]
            doc "Fetch the sealed configuration vault from the remote repository. Does not apply it."
            params {}

        "remote.diff" RemoteDiff => remote_diff -> RemoteDiff(RemoteDiffReply)
            flags [needs_unlock]
            doc "What applying the pulled configuration would change locally."
            params {}

        "remote.apply" RemoteApply => remote_apply -> RemoteStatus(RemoteStatusReply)
            flags [mutating, needs_unlock]
            doc "Apply the pulled configuration. Local run history is never overwritten by a pull."
            params {}

        "remote.push" RemotePush => remote_push -> RemoteStatus(RemoteStatusReply)
            flags [mutating, needs_unlock, elevated]
            doc "Publish the local sealed vault to the remote repository. Always explicit, never automatic."
            params {
                message: Option<String> = "Commit message; the daemon writes a default when omitted.",
            }

        // ------------------------------------------------------------- service
        "service.status" ServiceStatus => service_status -> Service(ServiceReply)
            flags []
            doc "Whether the background service is installed and running, and whether autostart is on."
            params {}

        "service.install" ServiceInstall => install_service -> Service(ServiceReply)
            flags [mutating, elevated]
            doc "Install the background service so backups run without anyone logged in. Requires administrative rights."
            params {}

        "service.uninstall" ServiceUninstall => uninstall_service -> Service(ServiceReply)
            flags [mutating, elevated]
            doc "Remove the background service. Configuration and backup data are untouched."
            params {}

        "service.set_autostart" ServiceSetAutostart => set_autostart -> Service(ServiceReply)
            flags [mutating]
            doc "Start the user-mode application at login, or stop doing so."
            params {
                enabled: bool = "True to start at login.",
            }
    }

    manual {
        "schema" Schema -> Schema
            flags []
            doc "Return the full command surface: every command, its parameters, their types and one-line descriptions."
            params {}

        "subscribe" Subscribe -> Subscribed
            flags [streaming]
            doc "Open a live stream of events, progress and status on this request id until cancelled."
            params {
                topics: Vec<Topic> = "Which classes of item to receive. An empty list means every topic.",
            }
    }
}

/// Build one [`ParamSpec`], normalising the stringified Rust type into
/// something a client author can read.
fn param(name: &str, ty: &str, summary: &str) -> ParamSpec {
    let compact: String = ty.chars().filter(|c| !c.is_whitespace()).collect();
    let optional = compact.starts_with("Option<");
    let secret = compact.contains("SecretString");
    // `Box<T>` is a layout decision with no wire meaning; showing it would
    // only confuse a client author in another language.
    let display = match compact.strip_prefix("Box<").and_then(|r| r.strip_suffix('>')) {
        Some(inner) => inner.to_string(),
        None => compact,
    };
    ParamSpec {
        name: name.to_string(),
        ty: display,
        summary: summary.trim().to_string(),
        optional,
        secret,
    }
}

/// The full, machine-readable command surface.
///
/// Generated, never written by hand. `superbackup help --json` prints this,
/// and `{"cmd":"schema"}` returns it.
pub fn schema() -> Schema {
    schema_with_limits(&Limits::default())
}

/// The command surface as served by a daemon configured with `limits`.
///
/// The server calls this so that `Schema::limits` reports the caps that are
/// actually in force, not the compiled-in defaults. A client that trusts the
/// schema and is then disconnected for exceeding a limit the schema did not
/// mention would have every right to be annoyed.
pub fn schema_with_limits(limits: &Limits) -> Schema {
    Schema {
        protocol: PROTOCOL_VERSION,
        min_protocol: MIN_PROTOCOL_VERSION,
        version: crate::VERSION.to_string(),
        commands: commands(),
        replies: reply_specs(),
        error_codes: ERROR_CODES.iter().map(|c| (*c).to_string()).collect(),
        topics: vec![
            TopicSpec {
                name: "events".to_string(),
                summary: "Activity-log lines as they are written.".to_string(),
            },
            TopicSpec {
                name: "progress".to_string(),
                summary: "Byte and file counters for running jobs. High volume.".to_string(),
            },
            TopicSpec {
                name: "status".to_string(),
                summary: "A full status snapshot whenever the aggregate picture changes."
                    .to_string(),
            },
        ],
        limits: LimitsSpec {
            max_line_bytes: limits.max_line_bytes,
            max_requests_per_second: limits.max_requests_per_second,
            request_burst: limits.request_burst,
            max_connections: limits.max_connections,
            stream_buffer: limits.stream_buffer,
        },
    }
}

// ===========================================================================
// Frames
// ===========================================================================

/// A line sent by a client.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientFrame {
    /// Ask the daemon to do something.
    Request {
        /// Unique among this connection's outstanding requests.
        id: RequestId,
        /// Protocol version the client speaks. Defaults to the version this
        /// build was compiled against when omitted, so a hand-typed line
        /// stays short; a real client should send it explicitly.
        #[serde(default = "default_protocol")]
        protocol: u32,
        body: Request,
    },
    /// End a subscription opened by an earlier `subscribe` with this id.
    ///
    /// Cancelling an id that is not a live subscription is not an error: it is
    /// the natural outcome of a race between the client cancelling and the
    /// stream ending on its own.
    Cancel { id: RequestId },
}

fn default_protocol() -> u32 {
    PROTOCOL_VERSION
}

/// A line sent by the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerFrame {
    /// Sent unprompted, immediately on accept, before the client speaks.
    ///
    /// A client compares its own version against `[min_protocol, protocol]`
    /// and gives up with a clear message if it falls outside — *before* it has
    /// sent a passphrase or a destructive command to a daemon it does not
    /// understand.
    Hello {
        protocol: u32,
        min_protocol: u32,
        version: String,
        /// True when this is the machine-wide service instance. A client can
        /// use it to explain which daemon it is talking to when both a tray
        /// and a service are installed.
        service_scope: bool,
    },
    /// A request succeeded.
    Ok { id: RequestId, body: Box<Reply> },
    /// A request failed. `id` is `0` for a failure that could not be
    /// attributed to a request — an unparseable line, a rate-limit rejection
    /// before the id was read.
    Error { id: RequestId, body: ErrorPayload },
    /// One item of a subscription.
    Stream { id: RequestId, body: Box<StreamItem> },
    /// A subscription ended: the client cancelled, or the daemon is shutting
    /// down. No further frames will carry this id.
    End { id: RequestId },
    /// The daemon is closing this connection. Sent on graceful shutdown so a
    /// client can say "the service stopped" rather than "the pipe broke".
    Bye { reason: String },
}

impl ServerFrame {
    /// Run [`crate::redact::scrub`] over every field that can carry
    /// third-party text.
    ///
    /// The transport calls this on every outbound frame, so redaction is a
    /// property of the socket rather than a discipline each handler has to
    /// remember. Handlers that already scrubbed lose nothing: `scrub` is
    /// idempotent.
    pub fn sanitise(mut self) -> ServerFrame {
        match &mut self {
            ServerFrame::Ok { body, .. } => body.sanitise(),
            ServerFrame::Stream { body, .. } => body.sanitise(),
            ServerFrame::Error { body, .. } => {
                scrub_in_place(&mut body.message);
                scrub_opt(&mut body.hint);
                scrub_opt(&mut body.detail);
            }
            ServerFrame::Bye { reason } => scrub_in_place(reason),
            // Nothing but ids and version numbers this process authored.
            ServerFrame::Hello { .. } | ServerFrame::End { .. } => {}
        }
        self
    }

    /// Convenience for the transport: an error frame from a core error.
    pub fn error(id: RequestId, error: &Error) -> ServerFrame {
        ServerFrame::Error { id, body: ErrorPayload::from_error(error) }
    }
}

/// Check a client's protocol version against what this build speaks.
///
/// Returns a [`ErrorCode::Ipc`] error naming both sides, because "protocol
/// mismatch" on its own sends a user hunting through logs while "client speaks
/// 3, this daemon speaks 1..=1, upgrade the daemon" tells them what to do.
pub fn check_protocol(client: u32) -> Result<()> {
    if client < MIN_PROTOCOL_VERSION {
        return Err(Error::Ipc(format!(
            "client speaks IPC protocol {client}, which this daemon (protocol \
             {MIN_PROTOCOL_VERSION}..={PROTOCOL_VERSION}) no longer supports; upgrade the client"
        )));
    }
    if client > PROTOCOL_VERSION {
        return Err(Error::Ipc(format!(
            "client speaks IPC protocol {client}, which is newer than this daemon \
             (protocol {MIN_PROTOCOL_VERSION}..={PROTOCOL_VERSION}); upgrade the daemon"
        )));
    }
    Ok(())
}
