//! Machine-readable description of the IPC command surface.
//!
//! The whole point of this module is that **nothing here is written by hand**.
//! Every [`CommandSpec`] is generated by the same `protocol!` macro invocation
//! that generates [`Request`](super::Request), the [`Handler`](super::Handler)
//! trait and the dispatcher, so the three can never disagree. If a command
//! exists, it is in the schema; if it is in the schema, a handler method
//! exists for it.
//!
//! Consumers:
//!
//! * `superbackup help --json` prints [`Schema`] verbatim.
//! * An AI agent asks for `{"cmd":"schema"}` once on connect and then knows
//!   every command, every parameter, every parameter type and which commands
//!   mutate state — without a bundled copy of this documentation that could
//!   rot.
//! * A client generator in another language can emit typed stubs from it.
//!
//! The schema deliberately describes *types by name* rather than embedding a
//! full JSON Schema. Names like `Job` or `BandwidthSettings` resolve to the
//! serde representation of [`crate::model`], which is already documented and
//! is the same shape the daemon persists. Inventing a second, partial type
//! language here would be a new source of drift.

use serde::{Deserialize, Serialize};

/// Everything a client needs to drive the daemon, in one message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Schema {
    /// Protocol version this daemon speaks. See
    /// [`PROTOCOL_VERSION`](super::PROTOCOL_VERSION).
    pub protocol: u32,
    /// Oldest protocol version this daemon still accepts from a client.
    pub min_protocol: u32,
    /// Build version of the daemon (`CARGO_PKG_VERSION`).
    pub version: String,
    /// Every request the daemon understands.
    pub commands: Vec<CommandSpec>,
    /// Every reply payload a command can produce.
    pub replies: Vec<ReplySpec>,
    /// Every value [`crate::error::ErrorCode`] can take, so a caller can
    /// exhaustively branch without reading Rust source.
    pub error_codes: Vec<String>,
    /// Topics accepted by `subscribe`.
    pub topics: Vec<TopicSpec>,
    /// Transport-level limits a client must respect. Exposed so a client can
    /// self-throttle instead of discovering the cap by being disconnected.
    pub limits: LimitsSpec,
}

/// One request the daemon understands.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandSpec {
    /// Wire value of the `cmd` field, e.g. `job.run`. Dotted areas group the
    /// surface for humans and for tab completion; they carry no meaning to
    /// the dispatcher.
    pub name: String,
    /// One line, imperative, no trailing full stop needed.
    pub summary: String,
    /// Parameters, in declaration order. A parameter whose `optional` flag is
    /// set may be omitted entirely (it is a Rust `Option<T>`, serialised as
    /// `null` or absent).
    pub params: Vec<ParamSpec>,
    /// The `reply` tag of the success payload this command produces.
    pub reply: String,
    /// Behavioural flags. See [`super::protocol::flag`] for the full list and
    /// what each one obliges a caller to do.
    pub flags: Vec<String>,
}

impl CommandSpec {
    /// Whether the command changes persistent state. A read-only agent can
    /// use this to refuse to call anything that writes.
    pub fn is_mutating(&self) -> bool {
        self.flags.iter().any(|f| f == "mutating")
    }

    /// Whether the command fails with [`crate::error::ErrorCode::Locked`]
    /// while the vault is locked.
    pub fn needs_unlock(&self) -> bool {
        self.flags.iter().any(|f| f == "needs_unlock")
    }
}

/// One parameter of one command.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParamSpec {
    /// JSON object key, exactly as serde expects it.
    pub name: String,
    /// Rust type name, normalised for readability: `Box<T>` is unwrapped
    /// because boxing is a memory-layout decision that has no wire effect,
    /// and whitespace is stripped. `Option<T>` is kept, because its absence
    /// from the JSON object is meaningful.
    pub ty: String,
    /// One line describing the parameter.
    pub summary: String,
    /// True for `Option<T>`: the key may be omitted or `null`.
    pub optional: bool,
    /// True when the value is secret material
    /// ([`SecretString`](super::SecretString)). A client must not log the
    /// request, and an agent must not echo the value back to a transcript.
    pub secret: bool,
}

/// One success payload shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplySpec {
    /// Wire value of the `reply` field.
    pub name: String,
    /// Name of the Rust struct carrying the payload; its fields are flattened
    /// alongside `reply` in the response body.
    pub payload: String,
    /// One line describing when this reply is produced.
    pub summary: String,
}

/// One `subscribe` topic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicSpec {
    pub name: String,
    pub summary: String,
}

/// Transport limits, published so clients can behave.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct LimitsSpec {
    /// Longest accepted line, in bytes, including the newline. A longer line
    /// is not truncated: the connection is closed, because a peer that sends
    /// one is either broken or hostile.
    pub max_line_bytes: usize,
    /// Requests per second a single connection may sustain.
    pub max_requests_per_second: u32,
    /// Burst above the sustained rate that is absorbed without error.
    pub request_burst: u32,
    /// Connections the daemon serves at once, across all clients.
    pub max_connections: usize,
    /// How many stream items are buffered for one subscriber before the
    /// oldest are dropped and a `lagged` marker is emitted.
    pub stream_buffer: usize,
}
